name: 🔶 pre-commit
description: '🔶 pre-commit stage from YaT.'

runs:
  using: composite
  steps:
    - uses: actions/checkout@v5
    - name: "🔶 pre-commit"
      run: |
        docker build -t yat:latest .
        docker run --rm yat:latest
      shell: bash
